### ISSUE TITLE
Use less abstract command line example as a base for our pills

### ISSUE THREAD

**Issue by paluh** [mhmdanas/purescript-transformers-pills#1]
I'm not sure if this would work better but we can consider using more real world options as a base for our pills. Something like for example a command line for spamming tool:

```
spam --subject "spam, spam, spam" --body "Dear recipient, we offer you this tasty spam!" --recipients recipient1@example.com recipeint2@example.com recipient3@example.com --smtp-server death.star.com --port 666 --password maps --user spammer
```
The above command line is quite nice because it make sens to group options to build more complex values etc. What do you think?

**Comment by mhmdanas** [comment]
Sounds like a good idea to me.

**Comment by mhmdanas** [comment]
Done in https://github.com/mhmdanas/purescript-transformers-pills/commit/f3015b8487892de4a19df4ef987ac47dd7e2f5f2.
