### ISSUE TITLE
Pill 2

### ISSUE THREAD

**Issue by mhmdanas** [mhmdanas/purescript-transformers-pills#3]
We have a couple options for pill 2:
- make `Parser` a `newtype` and start writing instances for it.
- introduce one of the transformers and write it and its instances.
- replace `Maybe` with `Either`.

What do you think @paluh? (If I forgot any other options, feel free to say them in a reply)

**Comment by paluh** [comment]
I'm opting for the first one. I'm just not sure if "`Tuple` parser" from the "Pill 1" exercises justifies this `newtype` enough.

What I think could **possibly** (I have not idea what kind of example could go here) motivate introduction of a `newtype` could be probably some example / exercise which benefits from the `Applicative` (like `sequence` or `traverse` usage - which is hardly the case in this context :-()). 
Another motivating option could be further complication of our `Parser` type and another reimplementation for "`Tuple` parser or even some `Parser SmptConfig` where `type SmtpConfig = { server :: String, port :: Int, password :: String, user :: String }`.
Following your "error handling" suggestion we can provide / propose these kind of complications:

```purescript
type Error = String
type Parser a = Input -> V (List Error) a
```

or even add help text aggregation to the stack:

```purescript
type Parser a = Input -> (Tuple String (V (Array String) a))
```

Let think about this for a moment...

**Comment by mhmdanas** [comment]
> What I think could possibly (I have not idea what kind of example could go here) motivate introduction of a newtype could be probably some example / exercise which benefits from the Applicative (like sequence or traverse usage - which is hardly the case in this context :-()).
This might actually be enough if we clarify that you'll have to pass an `Input` manually to every parser and that you won't be able to use functions such as `lift2`. Also, let's not forget that this is this exposes an implementation detail that end-users of `Parser` should not be aware of. What are your thoughts about this?
