### ISSUE TITLE
Pill 4

### ISSUE THREAD

**Issue by mhmdanas** [mhmdanas/purescript-transformers-pills#5]
I can't really remember what options we had, so let's discuss it here.

**Comment by paluh** [comment]
I think that we want to introduce gradually composition of and `Applicative` (and possibly later on introduce composition of `Monads` but probably in different context). Currently we have a stack of two `Applicative`s: `->` and `Either`.

* Should we add third `Applicative` to the stack like `help` builder (which is probably some form of a `Writer` - probably written by hand) to provide even stronger motivation (more boilerplate) for such a composition?
 
* Should we go and introduce `Compose` right away without adding additional layer?

**Comment by mhmdanas** [comment]
One slight problem with the `help` approach is that we'll have to make `Parser` a `newtype` or `data` if we want to write custom instances from it. I think at that point, the pill might be a bit too long.

**Comment by paluh** [comment]
We can use `Compose (Compose ...) ...` I think.
